services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env.local
    ports:
      - "8080:8080"

  database:
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_financeapp:/var/lib/postgresql/data

volumes:
  postgres_data_financeapp:
