# Generated by Django 5.2.5 on 2025-09-03 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('uscita', 'Spesa')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
                'unique_together': {('user', 'nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Conto',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('conto_corrente', 'Conto Corrente'), ('revolut', 'Revolut'), ('contanti', 'Contanti')], default='contanti', max_length=20)),
                ('valuta', models.CharField(default='EUR', max_length=10)),
                ('saldo_iniziale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conti',
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('spesa', 'Spesa')], max_length=10)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='api.categoria')),
                ('conto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='api.conto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
