# Generated by Django 5.2.4 on 2026-05-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True, help_text='Permetti nuove registrazioni')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('uscita', 'Spesa'), ('giroconto', 'Giroconto')], max_length=10)),
                ('color', models.CharField(default='#1FBC9C', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
                'unique_together': {('user', 'nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Conto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('conto_corrente', 'Conto Corrente'), ('revolut', 'Revolut'), ('contanti', 'Contanti')], default='contanti', max_length=20)),
                ('valuta', models.CharField(default='EUR', max_length=10)),
                ('saldo_iniziale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(default='#3498DB', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conti',
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.TextField()),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('uscita', 'Spesa'), ('giroconto', 'Giroconto')], max_length=10)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='api.categoria')),
                ('conto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='api.conto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_master_key', models.TextField(blank=True, help_text="Master Key encrypted with the user's password KEK", null=True)),
                ('recovery_encrypted_master_key', models.TextField(blank=True, help_text='Master Key encrypted with the Recovery Key KEK', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
