# Generated by Django 5.2.13 on 2026-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#1FBC9C', max_length=20),
        ),
        migrations.AddField(
            model_name='conto',
            name='color',
            field=models.CharField(default='#3498DB', max_length=20),
        ),
    ]
